version: '3.7'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: shade1471
      POSTGRES_PASSWORD: shade1471
      POSTGRES_DB: app

    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
